# -*- coding: utf-8 -*-
"""taro skripsi gru ode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dpUcRP_K8zABNbIIBPl1fmSPtNAE38jd
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.dates as mdates
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
import tensorflow as tf
from tensorflow import keras
from google.colab import files
import itertools, time, os, gc
tf.random.set_seed(42)
np.random.seed(42)
# -- 1. Upload Data ------------------------------------------
print("Upload your LQ45_combined_final.csv file:")
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)
df["Datetime"] = pd.to_datetime(df["Datetime"], utc=True)
df = df.sort_values("Datetime").reset_index(drop=True)
df = df[["Datetime", "Close"]].copy()
df["elapsed"] = df["Datetime"].diff().dt.total_seconds().fillna(300) / 3600.0
print(f"Loaded {len(df)} rows  |  {df['Datetime'].iloc[0]}  ->  {df['Datetime'].iloc[-1]}")
# -- 2. Scale & Build Sequences ------------------------------
FEATURES   = ["Close"]
TARGET_IDX = 0
SEQ_LEN    = 30
TRAIN_FRAC = 0.75
n_seq_total      = len(df) - SEQ_LEN
train_seq_end    = int(n_seq_total * TRAIN_FRAC)
raw_train_cutoff = SEQ_LEN + train_seq_end
scaler = MinMaxScaler()
scaler.fit(df[FEATURES].values[:raw_train_cutoff])
scaled = scaler.transform(df[FEATURES].values).astype(np.float32)
elapsed_arr = df["elapsed"].values.astype(np.float32)
def make_sequences(values, elapsed, seq_len):
    X, E, y = [], [], []
    for i in range(seq_len, len(values)):
        X.append(values[i - seq_len : i])
        E.append(elapsed[i - seq_len : i])
        y.append(values[i, TARGET_IDX])
    return np.array(X, np.float32), np.array(E, np.float32), np.array(y, np.float32)
X_all, E_all, y_all = make_sequences(scaled, elapsed_arr, SEQ_LEN)
N = len(X_all)
print(f"Total sequences: {N}")
# -- 3. GRU-ODE Cell with RK4 and Euler ------------------
class GRUODECell(tf.keras.layers.Layer):
    """
    GRU-ODE with selectable solver: 'euler', 'heun', 'rk4'.
    Uses num_unfolds sub-steps for integration.
    """
    def __init__(self, units, num_unfolds=4, solver="euler", **kwargs):
        super().__init__(**kwargs)
        self.units       = units
        self.num_unfolds = num_unfolds
        self.solver      = solver.lower()
    @property
    def state_size(self):  return self.units
    @property
    def output_size(self): return self.units
    def build(self, input_shape):
        feat_dim = input_shape[-1] - 1
        combined = feat_dim + self.units
        init_ones  = tf.constant_initializer(1.0)
        init_zeros = "zeros"
        init_g     = "glorot_uniform"
        self.W_r = self.add_weight(name="W_r", shape=(combined, self.units), initializer=init_g)
        self.b_r = self.add_weight(name="b_r", shape=(self.units,),          initializer=init_ones)
        self.W_z = self.add_weight(name="W_z", shape=(combined, self.units), initializer=init_g)
        self.b_z = self.add_weight(name="b_z", shape=(self.units,),          initializer=init_zeros)
        self.W_g = self.add_weight(name="W_g", shape=(combined, self.units), initializer=init_g)
        self.b_g = self.add_weight(name="b_g", shape=(self.units,),          initializer=init_zeros)
        self.built = True
    def _dh_dt(self, x, h):
        xh = tf.concat([x, h], axis=-1)
        r  = tf.sigmoid(xh @ self.W_r + self.b_r)
        z  = tf.sigmoid(xh @ self.W_z + self.b_z)
        g  = tf.tanh(tf.concat([x, r * h], axis=-1) @ self.W_g + self.b_g)
        return (1.0 - z) * (g - h)
    def _step_euler(self, x, h, dt):
        return h + dt * self._dh_dt(x, h)
    def _step_heun(self, x, h, dt):
        k1 = self._dh_dt(x, h)
        h_pred = h + dt * k1
        k2 = self._dh_dt(x, h_pred)
        return h + 0.5 * dt * (k1 + k2)
    def _step_rk4(self, x, h, dt):
        k1 = self._dh_dt(x, h)
        k2 = self._dh_dt(x, h + 0.5 * dt * k1)
        k3 = self._dh_dt(x, h + 0.5 * dt * k2)
        k4 = self._dh_dt(x, h + dt * k3)
        return h + (dt / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)
    def call(self, inputs, states):
        x       = inputs[:, :-1]
        elapsed = tf.reshape(inputs[:, -1], (-1, 1))

        elapsed = tf.clip_by_value(elapsed, 1e-4, 24.0)
        elapsed = tf.math.log1p(elapsed)
        dt      = elapsed / float(self.num_unfolds)
        h = states[0]
        if self.solver == "rk4":
            step = self._step_rk4
        elif self.solver == "heun":
            step = self._step_heun
        else:
            step = self._step_euler
        for _ in range(self.num_unfolds):
            h = step(x, h, dt)
        return h, [h]
    def get_config(self):
        cfg = super().get_config()
        cfg.update({"units": self.units, "num_unfolds": self.num_unfolds,
                    "solver": self.solver})
        return cfg
# -- 4. Model Builder ----------------------------------------
UNFOLDS = 4
def build_model(seq_len, n_features, units, dropout, solver):
    inp_x = keras.Input(shape=(seq_len, n_features), name="features")
    inp_e = keras.Input(shape=(seq_len,),            name="elapsed")
    elapsed_3d = keras.layers.Reshape((seq_len, 1))(inp_e)
    combined   = keras.layers.Concatenate(axis=-1)([inp_x, elapsed_3d])
    cell    = GRUODECell(units=units, num_unfolds=UNFOLDS, solver=solver)
    rnn_out = keras.layers.RNN(cell, return_sequences=False)(combined)
    # Simplified head: Dropout -> Dense(1)
    x   = keras.layers.Dropout(dropout)(rnn_out)
    out = keras.layers.Dense(1)(x)
    return keras.Model(inputs=[inp_x, inp_e], outputs=out, name="GRU_ODE")
# -- 5. Helpers ----------------------------------------------
def inverse_close(scaled_col):
    return scaler.inverse_transform(scaled_col.reshape(-1, 1)).flatten()
def compute_metrics(y_true, y_pred):
    mae  = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = np.mean(np.abs((y_true - y_pred) / (y_true + 1e-8))) * 100
    r2   = 1 - np.sum((y_true - y_pred)**2) / np.sum((y_true - np.mean(y_true))**2)
    return {"MAE": mae, "RMSE": rmse, "MAPE": mape, "R2": r2}
def split_data(tr_frac, va_frac):
    train_end = int(N * tr_frac)
    val_end   = int(N * (tr_frac + va_frac))
    return (X_all[:train_end],        E_all[:train_end],        y_all[:train_end],
            X_all[train_end:val_end],  E_all[train_end:val_end],  y_all[train_end:val_end],
            X_all[val_end:],           E_all[val_end:],           y_all[val_end:],
            train_end, val_end)
# -- 6. Hyperparameter Grid ---------------------------------
SPLITS    = [(0.75, 0.15, 0.10)]
assert abs(SPLITS[0][0] - TRAIN_FRAC) < 1e-9, "TRAIN_FRAC must match SPLITS train fraction (avoids leakage)"

HIDDENS   = [32, 64] #Nelson et al 2017
LRS       = [0.001, 0.01] #Siami Namini 2019, Bao 2017
EPOCHS    = [80]
BATCHES   = [32, 64] #Siami Namini 2019 #Nelson 2017
DROPOUTS  = [0.2, 0.1] #Bao 2017 #Nelson 2017
SOLVERS   = ["rk4", "euler"]
combos = list(itertools.product(SPLITS, HIDDENS, LRS, EPOCHS, BATCHES, DROPOUTS, SOLVERS))
TOTAL  = len(combos)
print(f"\nTotal combinations to try: {TOTAL}")
print(f"Estimated time: ~{TOTAL * 1.5:.0f}-{TOTAL * 4:.0f} minutes (depends on epochs/batch/GPU)\n")
CHECKPOINT_CSV = "gridsearch_full_results.csv"
# Resume support: if file exists, load completed combos
if os.path.exists(CHECKPOINT_CSV):
    done_df = pd.read_csv(CHECKPOINT_CSV)
    done_keys = set(zip(done_df["split_label"], done_df["hidden"], done_df["lr"],
                          done_df["epochs"], done_df["batch"], done_df["dropout"],
                          done_df["solver"]))
    print(f"Resuming -- {len(done_keys)} combos already completed.")
    grid_results = done_df.to_dict("records")
else:
    done_keys = set()
    grid_results = []
# -- 7. Run Grid Search -------------------------------------
print("="*78)
print(f"  FULL GRID SEARCH  ({TOTAL} combinations)")
print("="*78)
start_time = time.time()
best_val_mae = float("inf")
best_model   = None
best_history = None
best_config  = None
for idx, ((tr_f, va_f, te_f), hidden, lr, n_epochs, bs, dr, solver) in enumerate(combos):
    split_label = f"{int(tr_f*100)}/{int(va_f*100)}/{int(te_f*100)}"
    key = (split_label, hidden, lr, n_epochs, bs, dr, solver)
    if key in done_keys:

        existing = next((r for r in grid_results if (r["split_label"], r["hidden"], r["lr"],
                          r["epochs"], r["batch"], r["dropout"], r["solver"]) == key), None)
        if existing and existing["val_MAE"] < best_val_mae:
            best_val_mae = existing["val_MAE"]
            best_config  = existing
        continue
    elapsed = time.time() - start_time
    print(f"\n[{idx+1}/{TOTAL}] split={split_label} hid={hidden} lr={lr} "
          f"ep={n_epochs} bs={bs} dr={dr} solver={solver}  "
          f"(elapsed {elapsed/60:.1f}m)")
    X_tr, E_tr, y_tr, X_va, E_va, y_va, X_te, E_te, y_te, _, _ = split_data(tr_f, va_f)
    tf.random.set_seed(42)
    np.random.seed(42)
    keras.backend.clear_session()
    model = build_model(SEQ_LEN, len(FEATURES), hidden, dr, solver)
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=lr, clipnorm=1.0),
        loss="mse",
        metrics=["mae"]
    )
    callbacks = [
        keras.callbacks.EarlyStopping(monitor="val_loss", patience=12,
                                      restore_best_weights=True, verbose=0),
        keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5,
                                          patience=5, min_lr=1e-5, verbose=0),
    ]
    try:
        hist = model.fit(
            [X_tr, E_tr], y_tr,
            validation_data=([X_va, E_va], y_va),
            epochs=n_epochs,
            batch_size=bs,
            callbacks=callbacks,
            verbose=0,
        )
    except Exception as e:
        print(f"  X Failed: {e}")
        continue
    p_tr = inverse_close(model.predict([X_tr, E_tr], verbose=0).flatten())
    t_tr = inverse_close(y_tr)
    tm_tr = compute_metrics(t_tr, p_tr)
    p_va = inverse_close(model.predict([X_va, E_va], verbose=0).flatten())
    t_va = inverse_close(y_va)
    vm = compute_metrics(t_va, p_va)
    entry = {
        "split_label": split_label, "train_frac": tr_f, "val_frac": va_f, "test_frac": te_f,
        "hidden": hidden, "lr": lr, "epochs": n_epochs, "batch": bs,
        "dropout": dr, "solver": solver,
        "best_epoch": len(hist.history["loss"]),
        "best_val_loss": float(min(hist.history["val_loss"])),
        "train_MAE": tm_tr["MAE"], "train_RMSE": tm_tr["RMSE"], "train_MAPE": tm_tr["MAPE"], "train_R2": tm_tr["R2"],
        "val_MAE": vm["MAE"], "val_RMSE": vm["RMSE"], "val_MAPE": vm["MAPE"], "val_R2": vm["R2"],
    }
    grid_results.append(entry)

    pd.DataFrame(grid_results).to_csv(CHECKPOINT_CSV, index=False)
    print(f"   Val  MAE={vm['MAE']:.4f}  RMSE={vm['RMSE']:.4f}  "
          f"MAPE={vm['MAPE']:.4f}%  R^2={vm['R2']:.4f}")
    if vm["MAE"] < best_val_mae:
        best_val_mae = vm["MAE"]
        best_model   = model
        best_history = hist
        best_config  = entry
        print("   * New best!")
    else:
        del model
        gc.collect()
total_time = time.time() - start_time
print(f"\n{'='*78}")
print(f"  GRID SEARCH COMPLETE  *  {total_time/60:.1f} minutes total")
print(f"{'='*78}")
# -- 8. Final Evaluation on Test Set -------------------------
if best_model is not None:
    print("\nEvaluating Best Model on Unseen Test Set...")

    _, _, _, _, _, _, X_te, E_te, y_te, _, _ = split_data(best_config["train_frac"], best_config["val_frac"])
    p_te = inverse_close(best_model.predict([X_te, E_te], verbose=0).flatten())
    t_te = inverse_close(y_te)
    tm = compute_metrics(t_te, p_te)
    print(f"  Best Config: hidden={best_config['hidden']}, lr={best_config['lr']}, solver={best_config['solver']}, bs={best_config['batch']}, dr={best_config['dropout']}")
    print(f"  FINAL TEST MAE  = {tm['MAE']:.4f}")
    print(f"  FINAL TEST RMSE = {tm['RMSE']:.4f}")
    print(f"  FINAL TEST MAPE = {tm['MAPE']:.4f}%")
    print(f"  FINAL TEST R^2   = {tm['R2']:.4f}")
else:
    print("\nNo best model was found. Check for training errors.")

# -- 8. Data Prep for Plotting -------------------------------
print("Preparing data for final dashboard...")
# Re-fetch the exact splits for the best configuration
X_tr, E_tr, y_tr, X_va, E_va, y_va, X_te, E_te, y_te, train_end, val_end = split_data(
    best_config["train_frac"], best_config["val_frac"]
)
if best_model is None:
    print("best_model not found in memory (likely resumed from CSV). Retraining the best configuration...")
    tf.random.set_seed(42)
    np.random.seed(42)
    keras.backend.clear_session()
    best_model = build_model(SEQ_LEN, len(FEATURES), best_config["hidden"], best_config["dropout"], best_config["solver"])
    best_model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=best_config["lr"], clipnorm=1.0),
        loss="mse",
        metrics=["mae"]
    )
    callbacks = [
        keras.callbacks.EarlyStopping(monitor="val_loss", patience=12, restore_best_weights=True, verbose=0),
        keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=5, min_lr=1e-5, verbose=0),
    ]
    best_history = best_model.fit(
        [X_tr, E_tr], y_tr,
        validation_data=([X_va, E_va], y_va),
        epochs=best_config["epochs"],
        batch_size=best_config["batch"],
        callbacks=callbacks,
        verbose=1
    )
    print("Retraining complete!")
# Generate final predictions with the best model
p_tr = inverse_close(best_model.predict([X_tr, E_tr], verbose=0).flatten())
t_tr = inverse_close(y_tr)
tr_m = compute_metrics(t_tr, p_tr)
p_va = inverse_close(best_model.predict([X_va, E_va], verbose=0).flatten())
t_va = inverse_close(y_va)
va_m = compute_metrics(t_va, p_va)
p_te = inverse_close(best_model.predict([X_te, E_te], verbose=0).flatten())
t_te = inverse_close(y_te)
te_m = compute_metrics(t_te, p_te)
# Organize into dictionaries for the plot loops
trues   = {"Train": t_tr, "Val": t_va, "Test": t_te}
preds   = {"Train": p_tr, "Val": p_va, "Test": p_te}
results = {
    "Train": [tr_m["MAE"], tr_m["RMSE"], tr_m["MAPE"], tr_m["R2"]],
    "Val":   [va_m["MAE"], va_m["RMSE"], va_m["MAPE"], va_m["R2"]],
    "Test":  [te_m["MAE"], te_m["RMSE"], te_m["MAPE"], te_m["R2"]],
}
# Print the Evaluation Metrics to the console
print("\n" + "="*78)
print(f" FINAL EVALUATION METRICS (Best Config: {best_config['split_label']} | Hid:{best_config['hidden']} | LR:{best_config['lr']})")
print("="*78)
print(f" [TRAIN] MAE: {tr_m['MAE']:.4f}  |  RMSE: {tr_m['RMSE']:.4f}  |  MAPE: {tr_m['MAPE']:.4f}%  |  R^2: {tr_m['R2']:.4f}")
print(f" [VAL]   MAE: {va_m['MAE']:.4f}  |  RMSE: {va_m['RMSE']:.4f}  |  MAPE: {va_m['MAPE']:.4f}%  |  R^2: {va_m['R2']:.4f}")
print(f" [TEST]  MAE: {te_m['MAE']:.4f}  |  RMSE: {te_m['RMSE']:.4f}  |  MAPE: {te_m['MAPE']:.4f}%  |  R^2: {te_m['R2']:.4f}")
print("="*78 + "\n")
# Prep datetime arrays based on the indices
dt_all   = df["Datetime"].values[SEQ_LEN:]
dt_train = pd.to_datetime(dt_all[:train_end])
dt_val   = pd.to_datetime(dt_all[train_end:val_end])
dt_test  = pd.to_datetime(dt_all[val_end:])
# Prep Grid Search Results DataFrame (sorted by Val MAE, taking top 15 for readability)
results_df = pd.DataFrame(grid_results).sort_values("val_MAE").reset_index(drop=True)
plot_df = results_df.head(15).copy() # Top 15 combos
config_labels = [f"H{r['hidden']}|L{r['lr']}|{r['solver']}" for _, r in plot_df.iterrows()]
# -- 9. Plots ------------------------------------------------
plt.style.use("dark_background")
BG   = "#0D0D0D"
C1   = "#00C9FF"   # actual
C2   = "#FF6B6B"   # predicted / test
C3   = "#FFD700"   # val
def start_end_ticks(ax, dates):
    """Show only the start and end date as tick labels."""
    start_num = mdates.date2num(pd.Timestamp(dates[0]))
    end_num   = mdates.date2num(pd.Timestamp(dates[-1]))
    ax.set_xticks([start_num, end_num])
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%d %b %Y"))
    ax.tick_params(axis="x", rotation=0, labelsize=8)
fig = plt.figure(figsize=(20, 22), facecolor=BG)
fig.suptitle(f"GRU-ODE  *  LQ45 5-min Close  *  Best Split {best_config['split_label']}",
             fontsize=18, fontweight="bold", color="white", y=0.92)
gs  = gridspec.GridSpec(4, 2, figure=fig, hspace=0.40, wspace=0.25)
# (A) Loss curve
ax = fig.add_subplot(gs[0, :])
if best_history is not None:
    ep = range(1, len(best_history.history["loss"]) + 1)
    ax.plot(ep, best_history.history["loss"],     color=C1, lw=2, label="Train Loss")
    ax.plot(ep, best_history.history["val_loss"], color=C2, lw=2, label="Val Loss", ls="--")
ax.set_title("Training History (Best Config)", color="white")
ax.set_xlabel("Epoch"); ax.set_ylabel("MSE"); ax.legend(); ax.grid(alpha=0.2)
ax.set_facecolor(BG)
# (B) Train
ax = fig.add_subplot(gs[1, 0])
ax.plot(dt_train, trues["Train"], color=C1, lw=1.2, label="Actual")
ax.plot(dt_train, preds["Train"], color=C2, lw=1.2, label="Predicted", alpha=0.85)
ax.set_title(f"Train ({len(X_tr)} samples)", color="white")
ax.set_xlabel("Datetime"); ax.set_ylabel("Close (IDR pts)")
ax.legend(fontsize=8); ax.grid(alpha=0.2); ax.set_facecolor(BG)
start_end_ticks(ax, dt_train)
# (C) Validation
ax = fig.add_subplot(gs[1, 1])
ax.plot(dt_val, trues["Val"], color=C1, lw=1.2, label="Actual")
ax.plot(dt_val, preds["Val"], color=C3, lw=1.2, label="Predicted", alpha=0.85)
ax.set_title(f"Validation ({len(X_va)} samples)", color="white")
ax.set_xlabel("Datetime"); ax.set_ylabel("Close (IDR pts)")
ax.legend(fontsize=8); ax.grid(alpha=0.2); ax.set_facecolor(BG)
start_end_ticks(ax, dt_val)
# (D) Test
ax = fig.add_subplot(gs[2, 0])
ax.plot(dt_test, trues["Test"], color=C1, lw=1.5, label="Actual")
ax.plot(dt_test, preds["Test"], color=C2, lw=1.5, label="Predicted", alpha=0.85)
ax.set_title(f"Test ({len(X_te)} samples)", color="white")
ax.set_xlabel("Datetime"); ax.set_ylabel("Close (IDR pts)")
ax.legend(fontsize=8); ax.grid(alpha=0.2); ax.set_facecolor(BG)
start_end_ticks(ax, dt_test)
# (E) Metrics bar chart
ax  = fig.add_subplot(gs[2, 1])
x   = np.arange(3)
w   = 0.25
metric_labels = ["MAE", "RMSE", "MAPE (%)"]
colors_b = [C1, C3, C2]
for i, split in enumerate(["Train", "Val", "Test"]):
    vals = [results[split][0], results[split][1], results[split][2]]
    ax.bar(x + (i - 1) * w, vals, w, label=split, color=colors_b[i], alpha=0.85)
ax.set_xticks(x); ax.set_xticklabels(metric_labels)
ax.set_title("Performance Metrics (Best Config)", color="white")
ax.legend(fontsize=8); ax.grid(axis="y", alpha=0.2); ax.set_facecolor(BG)
# (F) Grid Search Comparison -- Train vs Val MAE (Top 15)
ax = fig.add_subplot(gs[3, 0])
# Check if "train_MAE" exists in the CSV checkpoint, default to 0 if not
train_maes = plot_df["train_MAE"].tolist() if "train_MAE" in plot_df.columns else [0] * len(plot_df)
val_maes   = plot_df["val_MAE"].tolist()
x_pos = np.arange(len(config_labels))
ax.bar(x_pos - 0.15, train_maes, 0.3, color=C1, alpha=0.85, label="Train MAE")
ax.bar(x_pos + 0.15, val_maes,   0.3, color=C3, alpha=0.85, label="Val MAE")
# Highlight best (which is index 0 since we sorted by val_MAE)
ax.bar(0 - 0.15, train_maes[0], 0.3, color=C1, edgecolor="white", linewidth=2)
ax.bar(0 + 0.15, val_maes[0],   0.3, color=C3, edgecolor="white", linewidth=2)
ax.set_xticks(x_pos); ax.set_xticklabels(config_labels, rotation=45, ha="right", fontsize=8)
ax.set_title("Grid Search: Train vs Val MAE (Top 15)", color="white")
ax.set_ylabel("MAE"); ax.legend(fontsize=8); ax.grid(axis="y", alpha=0.2); ax.set_facecolor(BG)
# (G) Grid Search Comparison -- Train vs Val R^2 (Top 15)
ax = fig.add_subplot(gs[3, 1])
# Check if "train_R2" exists in the CSV checkpoint, default to 0 if not
train_r2s = plot_df["train_R2"].tolist() if "train_R2" in plot_df.columns else [0] * len(plot_df)
val_r2s   = plot_df["val_R2"].tolist()
ax.bar(x_pos - 0.15, train_r2s, 0.3, color=C1, alpha=0.85, label="Train R^2")
ax.bar(x_pos + 0.15, val_r2s,   0.3, color=C3, alpha=0.85, label="Val R^2")
ax.bar(0 - 0.15, train_r2s[0],  0.3, color=C1, edgecolor="white", linewidth=2)
ax.bar(0 + 0.15, val_r2s[0],    0.3, color=C3, edgecolor="white", linewidth=2)
ax.set_xticks(x_pos); ax.set_xticklabels(config_labels, rotation=45, ha="right", fontsize=8)
ax.set_title("Grid Search: Train vs Val R^2 (Top 15)", color="white")
ax.set_ylabel("R^2"); ax.legend(fontsize=8); ax.grid(axis="y", alpha=0.2); ax.set_facecolor(BG)
fig.text(0.5, 0.08,
         f"SEQ_LEN={SEQ_LEN} | Units={best_config['hidden']} | Unfolds={UNFOLDS} | "
         f"Solver={best_config['solver']} | LR={best_config['lr']} | "
         f"Train={len(X_tr)} | Val={len(X_va)} | Test={len(X_te)}",
         ha="center", fontsize=10, color="gray")
plt.savefig("gruode_gridsearch_results.png", dpi=150, bbox_inches="tight", facecolor=BG)
plt.show()
# -- 10. Save Grid Search Results to CSV ---------------------
results_df.to_csv("gridsearch_split_results_sorted.csv", index=False)
print("\nTop Grid search results saved and sorted to gridsearch_split_results_sorted.csv")